name: Build container image test
on:
  registry_package:
    types: [published]
jobs:
  build-test:
    if: ${{ github.event.registry_package.name == 'misc/test-base' }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set TAG
        run: |
          echo "${{ github.actor }}"
          echo "github.event.registry_package.name ${{ github.event.registry_package.name }}"
          echo "github.event.registry_package.package_version.name ${{ github.event.registry_package.package_version.name }}"
          echo "github.event.registry_package.package_version.container_metadata.tag.name ${{ github.event.registry_package.package_version.container_metadata.tag.name }}"
          echo "github.event.registry_package.package_version.container_metadata.labels ${{ github.event.registry_package.package_version.container_metadata.labels }}"
          echo "TAG=${{ github.event.registry_package.package_version.container_metadata.tag.name }}" >> $GITHUB_ENV
      - uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - uses: docker/setup-buildx-action@v3
      - uses: docker/metadata-action@v5
        id: meta
        with:
          images: |
            ghcr.io/nishitaniyuki/misc/test
          tags: |
            type=raw,value=${{ env.TAG }}
          labels: |
            org.opencontainers.image.source=https://github.com/nishitaniyuki/misc
      - uses: docker/build-push-action@v6
        with:
          context: .
          file: ./build-container-image-test/Dockerfile
          build-args: |
            TAG=${{ env.TAG }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          platforms: linux/amd64
          push: true
          provenance: false
          cache-from: type=gha
          cache-to: type=gha,mode=max
